# Generated by Django 6.0.1 on 2026-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_adminnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnote',
            name='private_pin',
            field=models.CharField(max_length=128),
        ),
    ]
